// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_LabelConnect;
lv_obj_t * uic_ButtonConnect;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TabViewMain = NULL;
lv_obj_t * ui_TabPageConnect = NULL;
lv_obj_t * ui_ButtonConnect = NULL;
lv_obj_t * ui_LabelConnect = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_TabPageRun = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_ButtonConnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        hConnectBtn(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabViewMain = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabViewMain, 171);
    lv_obj_set_height(ui_TabViewMain, 320);
    lv_obj_set_align(ui_TabViewMain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabViewMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPageConnect = lv_tabview_add_tab(ui_TabViewMain, "Connection");

    ui_ButtonConnect = lv_btn_create(ui_TabPageConnect);
    lv_obj_set_width(ui_ButtonConnect, 100);
    lv_obj_set_height(ui_ButtonConnect, 50);
    lv_obj_set_align(ui_ButtonConnect, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ButtonConnect, LV_STATE_PRESSED);       /// States

    ui_LabelConnect = lv_label_create(ui_ButtonConnect);
    lv_obj_set_width(ui_LabelConnect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelConnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelConnect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelConnect, "CONNECT");

    ui_Label1 = lv_label_create(ui_TabPageConnect);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -100);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "00:00:00:00:00:00");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x2D9AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPageRun = lv_tabview_add_tab(ui_TabViewMain, "Run");

    ui_Label3 = lv_label_create(ui_TabPageRun);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -2);
    lv_obj_set_y(ui_Label3, -100);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "RUN");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x2D9AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonConnect, ui_event_ButtonConnect, LV_EVENT_ALL, NULL);
    uic_ButtonConnect = ui_ButtonConnect;
    uic_LabelConnect = ui_LabelConnect;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TabViewMain = NULL;
    ui_TabPageConnect = NULL;
    uic_ButtonConnect = NULL;
    ui_ButtonConnect = NULL;
    uic_LabelConnect = NULL;
    ui_LabelConnect = NULL;
    ui_Label1 = NULL;
    ui_TabPageRun = NULL;
    ui_Label3 = NULL;

}
